application:
  title: Development
  version: dev

sa-token:
  is-log: true

logging:
  level:
    root: debug
  file:
    path: target/log

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  api-docs:
    enabled: true

management:
  endpoints:
    enabled-by-default: true