server:
  port: ${SERVER_PORT:8080}
  http2:
    enabled: true

spring:
  banner:
    location: classpath:banner.txt
  main:
    banner-mode: LOG
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devilspiderx?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      database: 7

logging:
  file:
    path: ./log

sa-token:
  token-name: DSXSessionId
  is-concurrent: true
  is-share: false
  is-read-cookie: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: false
  group-configs:
    - group: 'default'
      display-name: '默认'
      paths-to-match: '/**'
      packages-to-scan: devilSpiderX.server.webServer

management:
  endpoints:
    enabled-by-default: false